services:
  # WHMCS server v8.8
  web8:
    image: fauzie/docker-whmcs:latest
    container_name: whmcs_web_8
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: localhost
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: ${WHMCS_DB_NAME}
      DB_USERNAME: ${WHMCS_DB_USER}
      DB_PASSWORD: ${WHMCS_DB_PASS}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./whmcs:/var/www/whmcs
    depends_on:
      - mysql_db
    networks:
      - whmcs_network

  # MySQL DB
  mysql_db:
    image: mysql:8.0
    container_name: whmcs_mysql_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${WHMCS_DB_NAME}
      MYSQL_USER: ${WHMCS_DB_USER}
      MYSQL_PASSWORD: ${WHMCS_DB_PASS}
      MYSQL_ROOT_PASSWORD: ${WHMCS_DB_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - whmcs_network

volumes:
  mysql_db_data:

networks:
  whmcs_network:
    driver: bridge